name: ci

on:
  push:
    branches: master
  
env:
   GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
   GKE_CLUSTER: cluster-1
   GKE_ZONE: us-centralc-1

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VCS
        uses: actions/checkout@master
      - name: Setup Google SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.SA_KEY}}       

        
  
    
