name: Build, push, and deploy
on: push

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: us-central1-c
  GOBUILDER_IMAGE: "golang:1.12-buster"

jobs:

  
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VCS
        uses: actions/checkout@master
      - name: Setup Google SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          
          service_account_key: ${{ secrets.SA_KEY }}
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@master
        with:
          kustomize-version: "3.2.1"
      - name: Make kustomize executable
        run: chmod +x /opt/hostedtoolcache/kustomize/3.2.1/x64/kustomize
        
      - name: Deploy to Dev Cluster
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE --project $GKE_PROJECT
          cd ./deploy
          export SHA_TAG="sha-${GITHUB_SHA::7}"
          export NAMESPACE="qmstr-$SHA_TAG"
          kubectl create namespace $NAMESPACE
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image endocodeci/qmstr-master:$SHA_TAG
          kustomize edit set image endocodeci/qmstr-client-mvn:$SHA_TAG
          kustomize edit set image endocodeci/pom-patch:$SHA_TAG
          kubectl apply -K .
          
          
